[normalize.data_writer]
disable_compression=true

[destination.filesystem]
bucket_url = "../data/" # replace with your bucket name,

[extract]
workers=1

[normalize]
workers=1

[load]
workers=1

[source]
max_table_nesting=1

[pipeline]
write_disposition="replace"